config/routes.rb
Rails.application.routes.draw do

  get 'system/privacy_policy'

  match '/auth/:provider', :to => 'sessions#omniauth_create',  via: [:post, :get]
  match '/auth/failure', :to => 'sessions#omniauth_failure',  via: [:post, :get]
  match "/signout" , :to => 'sessions#destroy', :as => :signout, via: [:post, :get]
  match "/privacy", :to => 'system#privacy_policy', :as => :privacy, via: [:get]
  match "/terms", :to => 'system#terms_of_service', :as => :terms, via: [:get]

  root :to => "videos#index", via: [:post, :get]
  resources :videos do
   resources :comments, only: [:destroy,:create], via: [:post,:get]
  end
  resources :channels
  resources :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/views/shared/_footer.html.erb
<footer class="footer">
      <div class="container">
<ul class="list-inline">
<li><button id="footer_about" type="button" class="btn btn-info"  data-toggle="modal" data-target="#aboutModal">How It Works?</button></li>
<li><button id="footer_feedback" type="button" class="btn btn-info"  data-toggle="modal" data-target="#contactUsModal">Contact Us</button></li>
<li><div class=" social social_link">
<a href="#"><i class="fa fa-lg fa-facebook"></i></a>
</div></li>
<li><div class=" social social_link">
<a href="#"><i class="fa fa-lg fa-twitter"></i></a>
</div></li>
<li><div class=" social social_link">
<a href="#"><i class="fa fa-lg fa-google-plus"></i></a>
</div></li>

</ul><!--list-->
        <div id="footer_details">
        My Short Flicks is the top website for online short films in India. The best short films on action , adventure , animation , comedy , crime , documentary , fantasy , horror , inspiration , mystery , parody , philosophy , political , romance , science-fiction , thriller . See the top reviewed films ; reviewed by acting , dialogues , story , direction , music and editing . Similar films can be grouped into productions which can then be followed by short movie admirers . Film-makers can see their works being reviewed and commented upon by thousands of short film addicts as they share their works in social media and get followers for their productions. Various competition test the skills of the best movie makers and win cash prizes and earn reputation . Get recognized and work with celebrities , Aim high and reach your goals , all here in Myshortflicks.com
        </div><!--footer details-->
      </div>
</footer>

app/views/shared/_header.html.erb
	<!-- feedback Modal -->
	<div class="modal fade" id="contactUsModal" tabindex="-1" role="dialog" aria-labelledby="contactUsModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title text-center" id="contactUsModalLabel">ContactUs</h4>
	      </div>
	      <div class="modal-body">
		#TODO
	      </div>
	      <div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>
	<!--modal-->

	<!-- About Modal -->
	<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title text-center" id="aboutModalLabel">How it works?</h4>
	      </div>
	      <div class="modal-body">
		#TODO
	      </div>
	      <div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>
	<!--modal-->
		<!-- Login Modal -->
		<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title text-center" id="loginModalLabel">Login to Awesomeness \m/</h4>
		      </div>
		      <div class="modal-body">
			<a href="/auth/facebook" class="btn btn-lg btn-primary login_button"><i class="fa fa-facebook fa-4x"></i>login</a>
			<a href="/auth/google_oauth2" class="btn btn-lg btn-danger login_button"><i class="fa fa-google-plus fa-4x"></i>login</a>
		      </div>
		      <div class="modal-footer">
			<div class="pull-left">	
			By logging in, you agree to the <%=link_to "privacy policy",privacy_path %> & <%=link_to "terms of service",terms_path %> 
			</div>
		      </div>
		    </div>
		  </div>
		</div>
		<!--modal-->
<div class="navbar navbar-inverse navbar-fixed-top">
   <div class="container">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         </button>
<a class="navbar-brand" href="<%=root_url%>"><img src="/assets/header_logo.jpg" alt="logo" class="header_logo"></img></a>
<!--a class="navbar-brand" href="<%=root_url%>">MSF</a-->
	<div class="navbar-form pull-right login_small_screen">
	  <button id="header_login" type="button" class="btn btn-primary"  data-toggle="modal" data-target="#loginModal">Login</button>

	</div><!--login-->
 
<div class="col-sm-3 col-md-3 pull-left">
<%= form_tag videos_path, :method => "get", :class =>"navbar-form", :id => "header_search_form" do %>
                <div class="input-group">
<%= text_field_tag :header_search_text, params[:search], :class => "form-control" %>



                    <span class="input-group-addon">
                       <div class="dropdown">
				
				<div class="dropdown-toggle cursor_pointer" data-toggle="dropdown" >
					<span class="caret"></span>
					<%#Default video search option%>
					<span id="header_selected_search_opter" ><i class="fa fa-video-camera"  ></i></span>
					
				</div>
				<%#list search options, js event handler will process selection%>
				<ul class="dropdown-menu center_search_drop_down bullet pull-center" role="menu" aria-labelledby="dropdownMenu1">
What are you looking for ?
<%#the value attrib of li element is used in header.js, dont change solely here%>
	    				<li  class="cursor_pointer search_options_select" value="film" role="presentation"><a role="menuitem" tabindex="-1" ><i class="fa fa-video-camera"></i> Films</a></li>
	   				 <li  class="cursor_pointer search_options_select" value="channel" role="presentation"><a role="menuitem" tabindex="-1" ><i class="fa fa-film"></i> Channels</a></li>
	   				 <li  class="cursor_pointer search_options_select" value="user" role="presentation"><a role="menuitem" tabindex="-1" ><i class="fa fa-users"></i> Users</a></li>

				</ul>
			</div>
                    </span>
		    <%# search icon %>
                    <span id="search_submit" class="input-group-addon">
                        <i class="fa fa-search"></i>
                    </span>
</div>



<%end%>
</div>


      </div>
      <div class="navbar-collapse collapse">



           <!--About-->
	<div class="navbar-form navbar-left">

	  <button id="header_about" type="button" class="btn btn-info"  data-toggle="modal" data-target="#aboutModal">About</button>



	</div><!--About-->
<div class="navbar-form navbar-left social social_link">
<a href="#"><i class="fa fa-lg fa-facebook"></i></a>
</div>
<div class="navbar-form navbar-left social social_link">
<a href="#"><i class="fa fa-lg fa-twitter"></i></a>
</div>
<div class="navbar-form navbar-left social social_link">
<a href="#"><i class="fa fa-lg fa-google-plus"></i></a>
</div>

<div class="dropdown navbar-form navbar-left social_dropdown">
  <div class="dropdown-toggle btn btn-primary" id="dropdownMenu2" data-toggle="dropdown" aria-expanded="true">
    Social
    <span class="caret"></span>
  </div>
  <ul class="dropdown-menu bullet pull-center text-center" role="menu" aria-labelledby="dropdownMenu2">
    <li role="presentation" class="social text-center"><a role="menuitem" tabindex="-1" href="#"><i class="fa fa-lg fa-facebook"></i></a></li>
    <li role="presentation" class="social text-center"><a role="menuitem" tabindex="-1" href="#"><i class="fa fa-lg fa-twitter"></i></a></li>
    <li role="presentation" class="social text-center"><a role="menuitem" tabindex="-1" href="#"><i class="fa fa-lg fa-google-plus"></i></a></li>
  </ul>
</div>


<!--div class="social navbar-form navbar-left">
    <ul class="list-inline">
        <li><a href="#"><i class="fa fa-lg fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-lg fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-lg fa-google-plus"></i></a></li>
   </ul>
</div-->
 	<!--login-->
	<div class="navbar-form navbar-right login_big_screen">
	  <button id="header_login" type="button" class="btn btn-primary"  data-toggle="modal" data-target="#loginModal">Login</button>

	</div><!--login--> 

 
      </div>
      <!--/.navbar-collapse -->

<%= render :partial => 'shared/header_discover' %>
   </div>
</div>

app/views/shared/_header_discover.html.erb
<ul class="list-inline discover_bar">
  <li value="featured"><%= link_to "Featured", videos_path(:filter => "featured") %>
  </li>
  <li value="feeds" style="display:none;">Feeds
  </li>
  <li value="video">Videos<span class="caret"></span>
<div id="video_option" class="discover_options">
<ul class="list-inline">

<li><%= link_to videos_path(:filter => "hottest_video") do %>
<div class="discover_option_choice">
<i class="fa fa-fire fa-4x"></i>
<div id="subtext">Hottest</div>
</div>  
<% end %></li>
<li><%= link_to videos_path(:filter => "top_rated_video") do %>
<div class="discover_option_choice">
<i class="fa fa-star fa-4x"></i>
<div id="subtext">Top Rated</div>
</div>  
<% end %></li>
<li><%= link_to videos_path(:filter => "most_viewed_video") do %>
<div class="discover_option_choice">
<i class="fa fa-eye fa-4x"></i>
<div id="subtext">Most Viewed</div>
</div> 
<% end %></li>
<li><%= link_to videos_path(:filter => "new_video") do %>
<div class="discover_option_choice">
<i class="fa fa-clock-o fa-4x"></i>
<div id="subtext">Recent</div>
</div> 
<% end %></li>

</ul>
</div>
</li>



<li value="category">Categories<span class="caret"></span>
<div id="category_option" class="discover_options">
<ul class="list-inline">

<% categories=get_category_list%>
<% categories.each do |category| %>

<li><%= link_to videos_path(:filter => "category_video",:category_id=>category.id) do %>
<div class="discover_option_choice">
<img src="<%=category.icon_url%>" />
<div id="subtext"><%=category.name%></div>
</div>  
<% end %></li>

<%end%>

</ul>
</div>
</li>

  <li value="channel">Channels<span class="caret"></span>
<div id="channel_option" class="discover_options">
<ul class="list-inline">
<li><%= link_to channels_path(:filter => "hottest_channel") do %>
<div class="discover_option_choice">
<i class="fa fa-fire fa-4x"></i>
<div id="subtext">Hottest</div>
</div>  
<% end %></li>
<li><%= link_to channels_path(:filter => "most_subscribed_channels") do %>
<div class="discover_option_choice">
<i class="fa fa-rss fa-4x"></i>
<div id="subtext">Most Subscribed</div>
</div>  
<% end %></li>
<li><%= link_to channels_path(:filter => "new_channel") do %>
<div class="discover_option_choice">
<i class="fa fa-clock-o fa-4x"></i>
<div id="subtext">Recent</div>
</div>  
<% end %></li>
</ul>
</div>



</li>



</ul>

app/views/shared/_loadmore.html.erb
<%= link_to "Load More", videos_path(:page=>2), :remote=> true, :method => "get", :class =>"load_more_btn  btn btn-default", :id => "load_more_link" %>

app/views/shared/_meta.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<% if isHome ==true && page.nil?  %>
<% content_for :head do %>
         <meta name="description" content="Login to My Short Flicks and access india's largest collection of short films, join and participate in competitions and meet like minded movie addicts @myshortflicks" />
         <meta name="keywords" content="free shortfilms, short films online,best short films,top short films,short films,shortfilms,videos,horror,comedy,thriller,anime,animation,short movies,small movies,short film india,short film hindi,short film telugu" />
	 <meta property="og:title" content="MyShortFlicks"/>	
	 <meta property="og:url" content="https://www.myshortflicks.com"/>	
	 <meta property="og:image" content="http://www.myshortflicks.com/images/msf_meta_image.jpg"/>
	 <meta property="og:description" content="Login to My Short Flicks and access india's largest collection of short films, join and participate in competitions and meet like minded movie addicts @myshortflicks" />

	<meta name="author" content="" />
	<meta name="copyright" content="" />
	<meta name="application-name" content="My Short Flicks" />
	<meta name="description" content="Login to My Short Flicks and access india's largest collection of short films, join and participate in competitions and meet like minded movie addicts @myshortflicks" />
	<meta name="keywords" content="free shortfilms, short films online,best short films,top short films,short films,shortfilms,videos,horror,comedy,thriller,anime,animation,short movies,small movies,short film india,short film hindi,short film telugu" />


         <meta name="twitter:card" content="summary" />
         <meta name="twitter:site" content="@MyShortFlicks" />
         <meta name="twitter:title" content="MyshortFlicks" />
         <meta name="twitter:description" content="Login to My Short Flicks and access india's largest collection of short films, join and participate in competitions and meet like minded movie addicts @myshortflicks" />
         <meta name="twitter:image" content="http://www.myshortflicks.com/images/msf_meta_image.jpg" />
         <meta name="twitter:url" content="https://www.myshortflicks.com" />


<% end %> 
<% elsif isHome ==false && !page.nil? && page.instance_of?(Video)%>

<% content_for :head do %>
	 <meta property="og:title" content="<%=page.title%>"/>	
	 <meta property="og:url" content="<%='#TODO'%>"/>	
	 <meta property="og:image" content="<%=page.video_thumbnail_url%>"/>
	 <meta property="og:description" content="<%=page.description%>" />

	<meta name="author" content="<%=page.title%>" />
	<meta name="copyright" content="" />
	<meta name="application-name" content="My Short Flicks" />
	<meta name="description" content="<%=page.description%>" />
	<meta name="keywords" content="<%=page.title%>" />

         <meta name="twitter:card" content="summary" />
         <meta name="twitter:site" content="@MyShortFlicks" />
         <meta name="twitter:title" content="<%=page.title%>" />
         <meta name="twitter:description" content="<%=page.description%>" />
         <meta name="twitter:image" content="<%=page.video_thumbnail_url%>" />
         <meta name="twitter:url" content="<%='#TODO'%>" />

<% end %> 
<%elsif isHome ==false && !page.nil? && page.instance_of?(User)%>
<% content_for :head do %>
	 <meta property="og:title" content="<%=page.first_name+" "+page.last_name%>"/>	
	 <meta property="og:url" content="<%='#TODO'%>"/>	
	 <meta property="og:image" content="<%=page.profile_image_url%>"/>
	 <meta property="og:description" content="<%=page.bio%>" />

	<meta name="author" content="<%=page.first_name+" "+page.last_name%>" />
	<meta name="copyright" content="" />
	<meta name="application-name" content="My Short Flicks" />
	<meta name="description" content="<%=page.bio%>" />
	<meta name="keywords" content="<%=page.first_name+" "+page.last_name%>" />

         <meta name="twitter:card" content="summary" />
         <meta name="twitter:site" content="@MyShortFlicks" />
         <meta name="twitter:title" content="<%=page.first_name+" "+page.last_name%>" />
         <meta name="twitter:description" content="<%=page.bio%>" />
         <meta name="twitter:image" content="<%=page.profile_image_url%>" />
         <meta name="twitter:url" content="<%='#TODO'%>" />

<% end %> 
<%elsif isHome ==false && !page.nil? && page.instance_of?(Channel)%>
<% content_for :head do %>
	 <meta property="og:title" content="<%=page.title%>"/>	
	 <meta property="og:url" content="<%='#TODO'%>"/>	
	 <meta property="og:image" content="<%=page.image_url%>"/>
	 <meta property="og:description" content="<%=page.description%>" />

	<meta name="author" content="<%=page.title%>" />
	<meta name="copyright" content="" />
	<meta name="application-name" content="My Short Flicks" />
	<meta name="description" content="<%=page.description%>" />
	<meta name="keywords" content="<%=page.title%>" />

         <meta name="twitter:card" content="summary" />
         <meta name="twitter:site" content="@MyShortFlicks" />
         <meta name="twitter:title" content="<%=page.title%>" />
         <meta name="twitter:description" content="<%=page.description%>" />
         <meta name="twitter:image" content="<%=page.image_url%>" />
         <meta name="twitter:url" content="<%='#TODO'%>" />

<% end %> 
<%end%>

app/views/shared/_noresult.html.erb
<div class="span7 center_no_result"> 
<div id="no_result_content"> No results </div>
 </div>